.TH science-config 1 "Apr 03, 2008" "Debian Science"
.SH NAME
.B science-config \- Debian Science common matapackage helper
.B science-<metapackage_name> \- package information and auto-apt helper

.SH SYNOPSIS
.B science-config
.B science-<metapackage_name>

.SH DESCRIPTION
Print just a simple information page about every science-* package
of the Debian Science Blend. Each metapackage contains a 
.I /usr/bin/science-<metapackage_name>
file which should print some useful information and could be used as auto-apt
helper.

.SH AUTHORS
Debian Science <debian-science@lists.debian.org>
