.TH science-config 1 "Oct 18, 2007" "Debian-Science"
.SH NAME
.B science-config
.B science-<meta_package_name>
\- package information and auto-apt helper

.SH SYNOPSIS
.B science-config
.B science-<meta_package_name>

.SH DESCRIPTION
Print just a simple information page about every science-* package
of the Debian-Science Custom Debian Distribution.  Each metapackage has a 
.I /usr/bin/science-<meta_package_name>
file which should print some usefull informations and could be serve
as auto-apt helper.

.SH AUTHORS
Debian-Science <debian-science@lists.debian.org>
